name: Rust CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
          
    - name: Build and test
      run: cargo test --verbose --all-features
      env:
        RUST_BACKTRACE: 1
        
    - name: Build release binary
      run: cargo build --release --verbose
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webshot-binary
        path: target/release/webshot
        retention-days: 7
